version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: starfleet-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: starfleet_gamifier
    volumes:
      - mongo_data:/data/db
    networks:
      - starfleet-net

volumes:
  mongo_data:
    driver: local

networks:
  starfleet-net:
    driver: bridge